apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
spec:
  selector:
    app: {{ include "name" . }}
    release: {{ .Release.Name }}
  ports:
  
    - protocol: TCP
      port: 9086
      targetPort: 9086
  type: {{ .Values.service.type }}
